"""tables — lookup tables rules can consult (``"lookup"`` condition), and their generators.

A table is ``data/tables/<name>.json``::

    {"_source": "where the data comes from", "entries": {"Mac16,7": {"model": "...", ...}}}

Keys are matched case-insensitively. A rule looks a value up with::

    "when": {"mdns_txt": {"model": "^(?P<m>\\w+\\d+,\\d+)$"},
             "lookup": {"table": "apple", "key": "{m}", "match": {"kind": "^laptop$"}}}

and may then use ``{lookup.model}``, ``{lookup.product}``, ... in its templates.

``apple.json`` is GENERATED by ``python -m netprint apple-update`` from AppleDB
(https://github.com/littlebyteorg/appledb, MIT; https://api.appledb.dev/device/main.json):
Apple model identifiers (``Mac16,7``, ``iPhone16,1``, ``Watch7,1``) to marketing names.
Do not edit it by hand; rerun the generator.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable
from functools import cache
from importlib import resources
from typing import Any

_PKG = __package__ or "netprint"

APPLEDB_URL = "https://api.appledb.dev/device/main.json"

# AppleDB "type" -> netprint category.
APPLE_KINDS: dict[str, str] = {
    "MacBook Pro": "laptop",
    "MacBook Air": "laptop",
    "MacBook": "laptop",
    "PowerBook": "laptop",
    "iBook": "laptop",
    "iMac": "desktop",
    "iMac Pro": "desktop",
    "Mac mini": "desktop",
    "Mac Pro": "desktop",
    "Mac Studio": "desktop",
    "eMac": "desktop",
    "PowerMac": "desktop",
    "Xserve": "desktop",
    "iPhone": "phone",
    "iPod touch": "phone",
    "iPad": "tablet",
    "iPad Pro": "tablet",
    "iPad Air": "tablet",
    "iPad mini": "tablet",
    "Apple Watch": "watch",
    "Apple TV": "media-player",
    "HomePod": "speaker",
    "AirPort": "router",
    "Apple Vision": "tablet",
}
_MONTHS = r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*"
_REGION = re.compile(r"\b(China|Mainland|Japan|Korea|Global|International)\b", re.I)


@cache
def load(name: str) -> dict[str, dict[str, str]]:
    """``{lowercased key: {field: value}}`` of ``data/tables/<name>.json`` ({} if missing)."""
    base = resources.files(_PKG).joinpath("data", "tables", f"{name}.json")
    try:
        raw = json.loads(base.read_text("utf-8"))
    except (FileNotFoundError, OSError, ValueError):
        return {}
    entries = raw.get("entries") if isinstance(raw, dict) else None
    out: dict[str, dict[str, str]] = {}
    for key, value in (entries or {}).items():
        row = value if isinstance(value, dict) else {"value": value}
        out[str(key).lower()] = {str(k): str(v) for k, v in row.items() if v is not None}
    return out


def names() -> list[str]:
    base = resources.files(_PKG).joinpath("data", "tables")
    try:
        return sorted(p.name[:-5] for p in base.iterdir() if p.name.endswith(".json"))
    except (FileNotFoundError, OSError):
        return []


def lookup(table: str, key: str) -> dict[str, str] | None:
    return load(table).get(key.strip().lower()) if key else None


def _pretty_apple(name: str, soc: str | None, released: str | None, kind: str) -> dict[str, str]:
    """'MacBook Pro (16-inch, M4 Pro, Nov 2024)' ->
    product 'MacBook Pro 16″', model 'MacBook Pro 16″ (M4 Pro, 2024)'."""
    m = re.fullmatch(r"(?P<base>[^(]*)\((?P<inner>[^)]*)\)(?P<tail>.*)", name)
    base = (m.group("base") if m else name).strip()
    parts = [p.strip() for p in (m.group("inner") if m else "").split(",") if p.strip()]
    tail = (m.group("tail") if m else "").strip()
    if tail:
        parts.append(tail)  # "iPad Pro 11-inch (M4) Wi-Fi"
    generation = None
    size = None
    m = re.search(r"(\d+(?:\.\d+)?)-inch", base)
    if m:
        size = m.group(1)
        base = re.sub(r"\s*\d+(?:\.\d+)?-inch", "", base).strip()
    details: list[str] = []
    year = None
    for part in parts:
        pm = re.fullmatch(r"(\d+(?:\.\d+)?)-inch", part)
        if pm:
            size = pm.group(1)
            continue
        ym = re.fullmatch(rf"(?:(?:Early|Mid|Late)\s+|{_MONTHS}\s+)?(\d{{4}})", part)
        if ym:
            year = ym.group(ym.lastindex or 1)
            continue
        if _REGION.search(part):
            continue
        if re.fullmatch(r"\d+(st|nd|rd|th) generation", part, re.I):
            generation = part
            continue
        details.append(part)
    if kind in ("laptop", "desktop"):
        if soc and not any(soc.lower() in d.lower() for d in details):
            details.insert(0, soc)
        if year is None and released:
            year = released[:4]
    product = f"{base} {size}″" if size else base
    if generation:
        product = f"{product} ({generation})"
        details.insert(0, generation)
        base_model = f"{base} {size}″" if size else base
        if year:
            details.append(year)
        return {"product": product, "model": f"{base_model} ({', '.join(details)})"}
    if year:
        details.append(year)
    model = f"{product} ({', '.join(details)})" if details else product
    return {"product": product, "model": model}


def build_apple_table(devices: Iterable[Any]) -> dict[str, dict[str, str]]:
    """AppleDB device records -> ``{identifier: {name, product, model, kind, soc}}``.

    One record per identifier: the one whose ``key`` IS the identifier (the base model, not
    a regional variant) wins."""
    out: dict[str, tuple[int, dict[str, str]]] = {}
    for dev in devices:
        if not isinstance(dev, dict):
            continue
        kind = APPLE_KINDS.get(str(dev.get("type") or ""))
        name = str(dev.get("name") or "").strip()
        if not kind or not name:
            continue
        ids = dev.get("identifier") or []
        if isinstance(ids, str):
            ids = [ids]
        released = dev.get("released")
        if isinstance(released, list):
            released = released[0] if released else None
        soc = str(dev["soc"]) if dev.get("soc") else None
        pretty = _pretty_apple(name, soc, str(released) if released else None, kind)
        for ident in ids:
            ident = str(ident)
            if not re.fullmatch(r"[A-Za-z]+\d+,\d+", ident):
                continue
            rank = 0 if str(dev.get("key") or "") == ident else 1
            if _REGION.search(name):
                rank += 2
            row = {"name": name, "kind": kind, **pretty}
            if soc:
                row["soc"] = soc
            if ident not in out or rank < out[ident][0]:
                out[ident] = (rank, row)
    return {k: v for k, (_rank, v) in sorted(out.items())}


def apple_document(table: dict[str, dict[str, str]]) -> dict[str, Any]:
    return {
        "_comment": "GENERATED by `python -m netprint apple-update`; do not edit by hand.",
        "_source": f"AppleDB (MIT, https://github.com/littlebyteorg/appledb): {APPLEDB_URL}",
        "entries": table,
    }
